spring:
  profiles:
    active: stage
  output:
    ansi:
      enabled: always
  thymeleaf:
    prefix: classpath:/templates

management:
  endpoints:
    web:
      exposure:
        include: logfile
  endpoint:
    logfile:
      external-file: logs/app.log