name: Deploy project

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build, tag, and push image
      id: build-image
      env:
        DOCKER_REGISTRY: serhiikirnos
        DOCKER_REPOSITORY: hash-tester-repo
      run: |
        docker build -t $DOCKER_REGISTRY/$DOCKER_REPOSITORY .
        docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY

    - name: Run project
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.STAGE_HOST }}
        user: ${{ secrets.STAGE_USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        command: |
          sudo docker stop $(sudo docker ps -q)
          sudo docker rm $(sudo docker ps -aq)
          sudo docker rmi $(sudo docker images -q)
          sudo docker pull mycoolstrongdocker/academy:latest
          sudo docker run -p 8080:8080 -v /data/logs:/logs -d --rm serhiikirnos/hash-tester-repo:latest
